### ISSUE TITLE
Database error when tag's search text being duplicated

### ISSUE THREAD

**Issue by semteacher** [andil-elearning/moodle-block_taggedcoursesearch#10]
#It is possible to enter the same tag search text twice:
- 1st pick up from standard tags
- 2nd input manually (in another registry, for example.)
![image](https://user-images.githubusercontent.com/1571998/80989585-ce173c80-8e3d-11ea-9633-9b969f892df0.png)
It led to database reading error
![image](https://user-images.githubusercontent.com/1571998/80989621-dbccc200-8e3d-11ea-8953-e897e3b345fd.png)

**Comment by ak4t0sh** [comment]
Nice catch !
Thanks for reporting this issue.
I’ll try to look at it but if in the meantime you already fixed it do not hesitate to fill a PR. :)

**Comment by semteacher** [comment]
Patch
[0001-added-extra-condition-to-avoid-duplication-of-tags-w.zip](https://github.com/andil-elearning/moodle-block_taggedcoursesearch/files/4728960/0001-added-extra-condition-to-avoid-duplication-of-tags-w.zip)

**Comment by ak4t0sh** [comment]
Thanks for the fix and your patience @semteacher ! I have to admit I totally forgot about this issue :s   
It has been integrated in release 1.1.1.
